/**
 * GET /api/musicxml/[id]
 *
 * Serves a pre-generated .musicxml file for a given song ID.
 *
 * The file is looked up in two locations (in order):
 *   1. <repo-root>/data/musicxml/<id>.musicxml   — generated by build_songbook.py
 *   2. <next-root>/public/musicxml/<id>.musicxml  — committed static assets
 *
 * Usage (browser):
 *   fetch("/api/musicxml/pal-pal-dil-ke-paas")
 *   // → Content-Type: application/vnd.recordare.musicxml+xml
 *
 * Usage (download link):
 *   href="/api/musicxml/pal-pal-dil-ke-paas"
 *   download="pal-pal-dil-ke-paas.musicxml"
 */

import { NextResponse } from "next/server";
import { existsSync, readFileSync } from "fs";
import path from "path";

// All MusicXML files must live in public/musicxml/ — they are copied there by
// prebuild.mjs from data/musicxml/.  This is the only path that works reliably
// in both local dev and Vercel/production (process.cwd() = platform/ in both).
function findMusicXml(safeId: string): string | null {
  const dir = path.join(process.cwd(), "public", "musicxml");
  const candidates = [
    path.join(dir, `${safeId}.musicxml`),
    path.join(dir, `${safeId}.mxl`),
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return null;
}

export async function GET(
  _request: Request,
  context: { params: Promise<{ id: string }> }
) {
  const { id } = await context.params;

  // Sanitise: allow only lowercase letters, digits, hyphens, underscores
  const safeId = id.replace(/[^a-z0-9_-]/gi, "");
  if (!safeId) {
    return NextResponse.json({ error: "Invalid song ID" }, { status: 400 });
  }

  const filePath = findMusicXml(safeId);

  if (!filePath) {
    return NextResponse.json(
      {
        error: "MusicXML not found",
        hint: "Run `python scripts/scrape_musicxml.py --generate --id <id>` to generate it.",
      },
      { status: 404 }
    );
  }

  try {
    const content = readFileSync(filePath, "utf-8");
    const isMxl = filePath.endsWith(".mxl");

    return new NextResponse(content, {
      status: 200,
      headers: {
        "Content-Type": isMxl
          ? "application/vnd.recordare.musicxml"
          : "application/vnd.recordare.musicxml+xml",
        "Content-Disposition": `attachment; filename="${safeId}.musicxml"`,
        // Allow caching for 1 hour since these files change rarely
        "Cache-Control": "public, max-age=3600",
      },
    });
  } catch (err) {
    console.error("[api/musicxml] read error:", err);
    return NextResponse.json(
      { error: "Failed to read MusicXML file" },
      { status: 500 }
    );
  }
}
